### ISSUE TITLE
put_events with ProcessPoolExecutor fails

### ISSUE THREAD

**Issue by calum-chamberlain** [niosh-mining/obsplus#158]
* obsplus version: current master
* Python version: 3.7
* Operating System: Ubuntu 18

### Description

While trying out the use of ProcessPoolExecutor's for putting events into a bank I came across a pickle error.

### What I Did

```python
from concurrent.futures import ProcessPoolExecutor
from obspy.clients.fdsn import Client
from obsplus import EventBank

client = Client("GEONET")
cat = client.get_events(eventid="2020p136748")

bank = EventBank("events")
bank.put_events(cat)
# Works fine

bank.executor = ProcessPoolExecutor()
bank.put_events(cat)
# Results in error below
```

```python
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/calumch/miniconda3/envs/conda_37/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/calumch/miniconda3/envs/conda_37/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'EventBank.put_events.<locals>.func'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-5-97da7aa49260> in <module>
      1 bank.executor = ProcessPoolExecutor()
----> 2 bank.put_events(cat)

~/my_programs/Building/obsplus/obsplus/bank/eventbank.py in put_events(self, events, update_index, bar)
    485         # create an iterator and apply over potential pool
    486         event_feeder = self._measure_iterator(events, bar)
--> 487         paths = list(self._map(func, event_feeder))
    488         if update_index:  # parse newly saved files and update index
    489             self.update_index(paths=paths)

~/miniconda3/envs/conda_37/lib/python3.7/concurrent/futures/process.py in _chain_from_iterable_of_lists(iterable)
    474     careful not to keep references to yielded objects.
    475     """
--> 476     for element in iterable:
    477         element.reverse()
    478         while element:

~/miniconda3/envs/conda_37/lib/python3.7/concurrent/futures/_base.py in result_iterator()
    584                     # Careful not to keep a reference to the popped future
    585                     if timeout is None:
--> 586                         yield fs.pop().result()
    587                     else:
    588                         yield fs.pop().result(end_time - time.monotonic())

~/miniconda3/envs/conda_37/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

~/miniconda3/envs/conda_37/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

~/miniconda3/envs/conda_37/lib/python3.7/multiprocessing/queues.py in _feed(buffer, notempty, send_bytes, writelock, close, ignore_epipe, onerror, queue_sem)
    234 
    235                         # serialize the data before acquiring the lock
--> 236                         obj = _ForkingPickler.dumps(obj)
    237                         if wacquire is None:
    238                             send_bytes(obj)

~/miniconda3/envs/conda_37/lib/python3.7/multiprocessing/reduction.py in dumps(cls, obj, protocol)
     49     def dumps(cls, obj, protocol=None):
     50         buf = io.BytesIO()
---> 51         cls(buf, protocol).dump(obj)
     52         return buf.getbuffer()
     53 

AttributeError: Can't pickle local object 'EventBank.put_events.<locals>.func'

```

This error is coming from trying to Pickle the local `func` in `put_events` - it looks like this use of an Executor isn't tested at the moment.  It's not immediately clear to me how to fix this, hence posting rather than just submitting a fix. Suggestions welcome!

**Comment by d-chambers** [comment]
I haven't looked at it closely yet but we couldn't we just give the inner function `func` a proper name and make it a private method/function? That should solve the pickle problem.

**Comment by calum-chamberlain** [comment]
It's a good shout - I ran into `weakref` issues when I attempted to make it a method and call it as a partial (setting `df` as a fixed argument).

**Comment by d-chambers** [comment]
It appears `update_index` also doesn't work with a multiprocessing executor for the same reason.
